name: Build Chrome extension

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0
        with:
          version: 10

      - name: Setup node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 24
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Check
        run: pnpm check:all

      - name: Generate new internal version
        run: jq '.version  += ".${{ github.run_number }}"' package.json > package.json.tmp && mv package.json.tmp package.json

      - name: Build
        run: pnpm build:mv3
        env:
          VITE_DOMAIN_URL: ${{ secrets.DOMAIN_URL }}

      - name: Zip extension
        uses: cardinalby/webext-buildtools-pack-extension-dir-action@ff720c809940cd5a1cbb048e988cccc71837ade4 # 1.0.9
        with:
          extensionDir: 'dist-mv3'
          zipFilePath: 'extension.zip'

      - uses: cardinalby/webext-buildtools-chrome-crx-action@200e7173cbdb5acb91d381cf9f7a30080b025047 # v2.0.3
        with:
          zipFilePath: 'extension.zip'
          crxFilePath: 'extension.crx'
          privateKey: ${{ secrets.CHROME_CRX_PRIVATE_KEY }}
          updateXmlPath: 'update.xml'
          updateXmlCodebaseUrl: '${{ secrets.DOMAIN_URL }}/extension.crx'

      - name: Upload built artifacts
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: chrome_extension_tester
          path: |
            ./extension.crx
            ./update.xml
